/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ExtractedCssRule {
  hash: string
  css: string
  /**
   * V3 source map JSON for the generated CSS, if source map generation
   * succeeded. Attach to the virtual CSS module as a
   * `/*# sourceMappingURL=data:…;base64,… *\/` comment or serve as a
   * separate `.map` file.
   */
  map?: string
}

export declare function transform(filename: string, sourceCode: string): TransformResult

export interface TransformResult {
  code: string
  cssRules: Array<ExtractedCssRule>
  /**
   * V3 source map JSON for the transformed JS. Generated by oxc_codegen
   * from the original AST; covers all unchanged tokens perfectly.  The
   * Vite plugin should pass this through as `{ code, map }` so that Vite
   * can chain it with any upstream maps.
   */
  map?: string
}
