/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ExtractedCssRule {
  hash: string
  css: string
  /** V3 source map JSON for the generated CSS. */
  map?: string
}

export interface GlobalCssRule {
  hash: string
  css: string
  map?: string
}

export interface KeyframeRule {
  /** The hex suffix without "kf_" */
  hash: string
  /** The full animation name: "kf_<hash>" */
  name: string
  /** The full @keyframes block, minified */
  css: string
  map?: string
}

export declare function transform(filename: string, sourceCode: string, themeJson?: string | undefined | null, dir?: string | undefined | null): TransformResult

export interface TransformResult {
  code: string
  cssRules: Array<ExtractedCssRule>
  globalCss: Array<GlobalCssRule>
  keyframes: Array<KeyframeRule>
  /** V3 source map JSON for the transformed JS. */
  map?: string
}
